from tkinter import *
top=Tk()
top.geometry("1200x600")
top.title("VD ")
top.config(bg="black")
w=Label(top,text="Welcome Our page",font=("forte",20,"italic"),bg="black",fg="white")
w.place(x=500,y=20)
def login():
    t=Frame(top,bg="black",height=600,width=500)
    t.pack(fill=X)
    w=Label(top,text="Login Page",font=("forte",20,"italic"),bg="black",fg="white")
    n=Label(top,text="Username",font=("forte",20,"italic"),bg="black",fg="white")
    d=Label(top,text="Don't have account? ",font=("Algerian",20,"italic"),bg="black",fg="white")
    P=Label(top,text="Password",font=("Algerian",20,"italic"),bg="black",fg="white")
    e=Entry(top,text="",font=("Algerian",20,"italic"),bg="white",fg="black")
    E=Entry(top,show="*",font=("Algerian",20,"italic"),bg="white",fg="black")
    w.place(x=500,y=20)
    n.place(x=300,y=100)
    P.place(x=300,y=180)
    d.place(x=300,y=500)
    e.place(x=500,y=100)
    E.place(x=500,y=180)
    b=Button(top,text="Login",font=("Algerian",20,"italic"),bg="green",fg="white",activebackground="aqua",activeforeground="white")
    B=Button(top,text="Sign in",font=("Algerian",20,"italic"),bg="orange",fg="white",activebackground="green",activeforeground="white")
    b.place(x=500,y=300)
    B.place(x=700,y=500)
b=Button(top,text="Get Started",font=("Algerian",20,"italic"),bg="white",fg="black",activebackground="green",activeforeground="white",command=login)
b.place(x=500,y=500)
